name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
USER_ID = "c55ba35f-12f6-436e-a451-4ce982c4ec1c"
